// catalog.mjs — scan worlds/*/world.json and (re)write worlds/index.json.
//
//   node harness/catalog.mjs           # write
//   node harness/catalog.mjs --check   # exit 1 if stale (CI / pre-commit)
//
// worlds/index.json is the ONE data contract: the gallery reads it, harness resolves
// names through it, and downstream sites (makone.xyz) consume the same shape.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const WORLDS = path.join(ROOT, 'worlds');

/** Fields promoted into the catalog. Anything else stays in the world's own world.json.
 *  All authored (D6): capabilities are probed by the harness, never declared here — so there is
 *  no `caps`. The probed/measured facts live in `verify.mjs`'s output and are folded in here only
 *  when a consumer needs them (nothing does yet; rule-of-three). */
const FIELDS = ['name', 'title', 'type', 'format', 'entry', 'cover', 'brief', 'tags'];

export async function buildCatalog() {
  const dirs = (await fs.readdir(WORLDS, { withFileTypes: true }))
    .filter((d) => d.isDirectory()).map((d) => d.name).sort();
  const worlds = [];
  for (const dir of dirs) {
    const file = path.join(WORLDS, dir, 'world.json');
    const raw = await fs.readFile(file, 'utf8').catch(() => null);
    if (!raw) { console.warn(`skip worlds/${dir}: no world.json`); continue; }
    const w = JSON.parse(raw);
    if (w.name !== dir) throw new Error(`worlds/${dir}/world.json has name "${w.name}" — must match the directory`);
    if (!/^[a-z0-9]+$/.test(w.name)) throw new Error(`world name "${w.name}" must be one lowercase word`);
    const entry = { path: dir };
    for (const k of FIELDS) if (w[k] !== undefined) entry[k] = w[k];
    worlds.push(entry);
  }
  return {
    $comment: 'GENERATED by harness/catalog.mjs — edit worlds/<name>/world.json, then re-run. '
      + 'type = what it is (scene|game|object). format = how it runs '
      + '(module: WorldModule dir, played via /play.html · page: self-contained html · classic: v1 single-file game).',
    generator: 'harness/catalog.mjs',
    count: worlds.length,
    worlds,
  };
}

const file = path.join(WORLDS, 'index.json');
const next = JSON.stringify(await buildCatalog(), null, 2) + '\n';

if (process.argv.includes('--check')) {
  const cur = await fs.readFile(file, 'utf8').catch(() => '');
  if (cur !== next) { console.error('worlds/index.json is stale — run: node harness/catalog.mjs'); process.exit(1); }
  console.log('worlds/index.json up to date');
} else {
  await fs.writeFile(file, next);
  console.log(`worlds/index.json — ${JSON.parse(next).count} worlds`);
}
